from __future__ import annotations

from codesentinelx_engine.models import Severity
from codesentinelx_engine.scanner.rules.base import RegexFileRule, RuleMetadata


CODE_EXTENSIONS = {
    ".py",
    ".js",
    ".jsx",
    ".ts",
    ".tsx",
    ".java",
    ".php",
    ".go",
    ".rb",
    ".cs",
    ".scala",
    ".kt",
    ".swift",
    ".sql",
    ".sh",
}

WEB_EXTENSIONS = {".js", ".jsx", ".ts", ".tsx", ".html", ".htm", ".php", ".vue"}
CONFIG_EXTENSIONS = {
    ".json",
    ".yaml",
    ".yml",
    ".ini",
    ".conf",
    ".env",
    ".toml",
    ".cfg",
    ".properties",
    ".xml",
    ".py",
    ".js",
}


def _rule(
    *,
    rule_id: str,
    vulnerability_type: str,
    severity: Severity,
    description: str,
    business_impact: str,
    recommendation: str,
    reference: str,
    owasp_category: str,
    cwe: str,
    patterns: list[str],
    file_extensions: set[str],
) -> RegexFileRule:
    return RegexFileRule(
        metadata=RuleMetadata(
            rule_id=rule_id,
            vulnerability_type=vulnerability_type,
            severity=severity,
            description=description,
            business_impact=business_impact,
            recommendation=recommendation,
            reference=reference,
            owasp_category=owasp_category,
            cwe=cwe,
        ),
        patterns=patterns,
        file_extensions=file_extensions,
    )


def build_builtin_file_rules() -> list[RegexFileRule]:
    return [
        _rule(
            rule_id="OWASP-A03-SQLI-001",
            vulnerability_type="SQL Injection",
            severity=Severity.CRITICAL,
            description="Dynamic SQL query construction can allow attacker-controlled query manipulation.",
            business_impact="Attackers may read, modify, or delete sensitive business and customer data.",
            recommendation="Use parameterized queries / prepared statements and strict input validation.",
            reference="https://owasp.org/Top10/A03_2021-Injection/",
            owasp_category="A03:2021 - Injection",
            cwe="CWE-89",
            patterns=[
                r"(cursor|statement)\.execute\s*\(.*\+.*\)",
                r"\b(SELECT|INSERT|UPDATE|DELETE)\b.*(\+|\.format\(|f\"|f\')",
                r"sequelize\.query\s*\(.*\+.*\)",
            ],
            file_extensions=CODE_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A03-XSS-001",
            vulnerability_type="Cross-Site Scripting (XSS)",
            severity=Severity.HIGH,
            description="Unsafely rendering user-controlled HTML/JS can execute attacker scripts in user browsers.",
            business_impact="Session hijacking, data theft, and unauthorized user actions can occur.",
            recommendation="Use output encoding, CSP, and framework-safe rendering APIs.",
            reference="https://owasp.org/www-community/attacks/xss/",
            owasp_category="A03:2021 - Injection",
            cwe="CWE-79",
            patterns=[
                r"innerHTML\s*=",
                r"document\.write\s*\(",
                r"dangerouslySetInnerHTML",
                r"v-html\s*=",
            ],
            file_extensions=WEB_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A03-CMDI-001",
            vulnerability_type="Command Injection",
            severity=Severity.CRITICAL,
            description="Passing untrusted input to OS command execution APIs may allow arbitrary command execution.",
            business_impact="Remote code execution may lead to full server compromise and lateral movement.",
            recommendation="Avoid shell execution with untrusted input and use safe API arguments.",
            reference="https://owasp.org/Top10/A03_2021-Injection/",
            owasp_category="A03:2021 - Injection",
            cwe="CWE-78",
            patterns=[
                r"os\.system\s*\(",
                r"subprocess\.(run|Popen|call)\s*\(.*shell\s*=\s*True",
                r"Runtime\.getRuntime\(\)\.exec\s*\(",
                r"child_process\.exec\s*\(",
            ],
            file_extensions=CODE_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A01-PATHTRAV-001",
            vulnerability_type="Path Traversal",
            severity=Severity.HIGH,
            description="User-controlled file paths can enable unauthorized file read/write access.",
            business_impact="Sensitive files and credentials may be exposed, modified, or destroyed.",
            recommendation="Normalize and validate paths against an allowlisted base directory.",
            reference="https://owasp.org/www-community/attacks/Path_Traversal",
            owasp_category="A01:2021 - Broken Access Control",
            cwe="CWE-22",
            patterns=[
                r"send_file\s*\(\s*request\.(args|form|values)",
                r"open\s*\(\s*request\.(args|form|values)",
                r"fs\.(readFile|readFileSync|createReadStream)\s*\(\s*req\.(query|params|body)",
                r"\.\./",
            ],
            file_extensions=CODE_EXTENSIONS | WEB_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A02-SECRETS-001",
            vulnerability_type="Hardcoded Secrets / Credentials",
            severity=Severity.HIGH,
            description="Embedded credentials can be extracted and reused by attackers.",
            business_impact="Credential leakage can enable unauthorized environment access and data breach.",
            recommendation="Move secrets to a managed secret store and rotate exposed credentials.",
            reference="https://owasp.org/Top10/A02_2021-Cryptographic_Failures/",
            owasp_category="A02:2021 - Cryptographic Failures",
            cwe="CWE-798",
            patterns=[
                r"\b(password|passwd|secret|api[_-]?key|token|client_secret)\b\s*[:=]\s*['\"][^'\"]{8,}['\"]",
                r"AKIA[0-9A-Z]{16}",
                r"-----BEGIN (RSA|DSA|EC|OPENSSH) PRIVATE KEY-----",
            ],
            file_extensions=CODE_EXTENSIONS | CONFIG_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A08-DESER-001",
            vulnerability_type="Insecure Deserialization",
            severity=Severity.HIGH,
            description="Deserializing untrusted data can lead to arbitrary code execution.",
            business_impact="Attackers may execute code, alter application state, or escalate privileges.",
            recommendation="Use safe serializers and enforce strict schema validation.",
            reference="https://owasp.org/www-project-top-ten/2017/A8_2017-Insecure_Deserialization",
            owasp_category="A08:2021 - Software and Data Integrity Failures",
            cwe="CWE-502",
            patterns=[
                r"pickle\.loads\s*\(",
                r"yaml\.load\s*\(",
                r"ObjectInputStream",
                r"BinaryFormatter",
            ],
            file_extensions=CODE_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A03-EVAL-001",
            vulnerability_type="Unsafe eval usage",
            severity=Severity.HIGH,
            description="Dynamic code execution primitives can execute attacker-controlled payloads.",
            business_impact="Potential remote code execution and complete application compromise.",
            recommendation="Replace eval/exec patterns with strict parsing and safe dispatch logic.",
            reference="https://owasp.org/Top10/A03_2021-Injection/",
            owasp_category="A03:2021 - Injection",
            cwe="CWE-95",
            patterns=[
                r"\beval\s*\(",
                r"\bexec\s*\(",
                r"new\s+Function\s*\(",
                r"setTimeout\s*\(\s*['\"]",
            ],
            file_extensions=CODE_EXTENSIONS | WEB_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A01-AUTH-001",
            vulnerability_type="Authentication / Authorization Flaw",
            severity=Severity.HIGH,
            description="Bypass flags and weak authorization controls can expose protected operations.",
            business_impact="Unauthorized users may access privileged functionality or sensitive data.",
            recommendation="Enforce centralized authz checks and remove bypass toggles from production paths.",
            reference="https://owasp.org/Top10/A01_2021-Broken_Access_Control/",
            owasp_category="A01:2021 - Broken Access Control",
            cwe="CWE-285",
            patterns=[
                r"\b(skip_auth|auth_disabled|disable_auth|allow_anonymous|permitAll)\b",
                r"jwt\.decode\s*\(.*verify\s*=\s*False",
                r"csrf\s*=\s*False",
                r"@PermitAll",
            ],
            file_extensions=CODE_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A05-MISCONFIG-001",
            vulnerability_type="Security Misconfiguration",
            severity=Severity.MEDIUM,
            description="Insecure defaults can expose sensitive internals and weaken defense layers.",
            business_impact="Increases attack surface and often enables chained exploitation.",
            recommendation="Harden runtime config, disable debug modes, and enforce secure defaults.",
            reference="https://owasp.org/Top10/A05_2021-Security_Misconfiguration/",
            owasp_category="A05:2021 - Security Misconfiguration",
            cwe="CWE-16",
            patterns=[
                r"debug\s*=\s*True",
                r"FLASK_ENV\s*=\s*['\"]development['\"]",
                r"NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*['\"]?0",
                r"Access-Control-Allow-Origin\s*[:=]\s*['\"]\*['\"]",
                r"ssl_verify\s*=\s*False",
            ],
            file_extensions=CODE_EXTENSIONS | CONFIG_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A10-SSRF-001",
            vulnerability_type="Server-Side Request Forgery (SSRF)",
            severity=Severity.HIGH,
            description="Backend makes outbound requests directly from user-controlled input.",
            business_impact="Attackers can pivot into internal services, metadata endpoints, and private networks.",
            recommendation="Allowlist destinations, block internal ranges, and validate URL schemes and hosts.",
            reference="https://owasp.org/Top10/A10_2021-Server-Side_Request_Forgery_%28SSRF%29/",
            owasp_category="A10:2021 - Server-Side Request Forgery",
            cwe="CWE-918",
            patterns=[
                r"requests\.(get|post|put|delete|request)\s*\(\s*(request|req)\.(args|query|body|form|values|params)",
                r"httpx\.(get|post|put|delete|request)\s*\(\s*(request|req)\.(args|query|body|form|values|params)",
                r"urllib\.request\.urlopen\s*\(\s*(request|req)\.(args|query|body|form|values|params)",
                r"axios\.(get|post|request)\s*\(\s*(req|request)\.(query|body|params)",
            ],
            file_extensions=CODE_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A02-WEAK-CRYPTO-001",
            vulnerability_type="Weak Cryptography Usage",
            severity=Severity.HIGH,
            description="Legacy or broken cryptographic primitives are used in backend code.",
            business_impact="Weak crypto enables faster credential cracking, token forgery, and data compromise.",
            recommendation="Use modern algorithms (AES-GCM, SHA-256+, Argon2/bcrypt/PBKDF2) and managed key rotation.",
            reference="https://owasp.org/Top10/A02_2021-Cryptographic_Failures/",
            owasp_category="A02:2021 - Cryptographic Failures",
            cwe="CWE-327",
            patterns=[
                r"hashlib\.(md5|sha1)\s*\(",
                r"crypto\.createHash\s*\(\s*['\"](md5|sha1)['\"]",
                r"MessageDigest\.getInstance\s*\(\s*\"(MD5|SHA-1)\"",
                r"\bDES\b",
                r"\bRC4\b",
            ],
            file_extensions=CODE_EXTENSIONS | CONFIG_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A02-INSECURE-RNG-001",
            vulnerability_type="Insecure Randomness for Security-Sensitive Data",
            severity=Severity.MEDIUM,
            description="Non-cryptographic random generators appear in security-sensitive flows.",
            business_impact="Predictable tokens, reset links, or OTP values can be brute-forced or guessed.",
            recommendation="Use cryptographic RNG APIs (secrets, os.urandom, crypto.randomBytes, SecureRandom).",
            reference="https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html",
            owasp_category="A02:2021 - Cryptographic Failures",
            cwe="CWE-330",
            patterns=[
                r"random\.(random|randint|choice)\s*\(",
                r"Math\.random\s*\(",
                r"new\s+Random\s*\(",
                r"rand\s*\(",
            ],
            file_extensions=CODE_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A07-JWT-001",
            vulnerability_type="JWT Validation Misconfiguration",
            severity=Severity.HIGH,
            description="JWT validation settings allow signature bypass or weak token acceptance.",
            business_impact="Attackers can forge or replay tokens to gain unauthorized access.",
            recommendation="Enforce signature validation, strict issuer/audience checks, and accepted algorithm allowlists.",
            reference="https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/",
            owasp_category="A07:2021 - Identification and Authentication Failures",
            cwe="CWE-347",
            patterns=[
                r"jwt\.decode\s*\(.*verify\s*=\s*False",
                r"verify_signature\s*[:=]\s*False",
                r"algorithms\s*[:=]\s*\[\s*['\"]none['\"]",
                r"algorithm\s*=\s*['\"]none['\"]",
            ],
            file_extensions=CODE_EXTENSIONS | CONFIG_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A01-OPENREDIRECT-001",
            vulnerability_type="Open Redirect",
            severity=Severity.MEDIUM,
            description="User-controlled redirect targets are used without strict allowlisting.",
            business_impact="Attackers can launch phishing flows and token theft via trusted application domains.",
            recommendation="Allowlist redirect destinations and validate scheme/host before redirecting.",
            reference="https://owasp.org/www-community/attacks/Unvalidated_Redirects_and_Forwards_Cheat_Sheet",
            owasp_category="A01:2021 - Broken Access Control",
            cwe="CWE-601",
            patterns=[
                r"res\.redirect\s*\(\s*(req|request)\.(query|body|params)",
                r"redirect\s*\(\s*request\.(args|values|get|form)",
                r"Response\.Redirect\s*\(\s*(Request|request)\.",
            ],
            file_extensions=CODE_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A03-NOSQLI-001",
            vulnerability_type="NoSQL Injection",
            severity=Severity.HIGH,
            description="NoSQL queries are built from untrusted request objects without sanitization.",
            business_impact="Authentication bypass, unauthorized data exposure, and data tampering may occur.",
            recommendation="Validate input schema, reject operator injection, and use strict query builders.",
            reference="https://owasp.org/www-project-top-ten/2017/A1_2017-Injection",
            owasp_category="A03:2021 - Injection",
            cwe="CWE-943",
            patterns=[
                r"\$(where|regex|ne|gt|gte|lt|lte)\b",
                r"(collection|db)\.(find|findOne|update|aggregate)\s*\(\s*(req|request)\.(body|query|params)",
                r"bson\.loads\s*\(\s*(req|request)\.(body|query|params)",
            ],
            file_extensions=CODE_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A03-LDAPI-001",
            vulnerability_type="LDAP Injection",
            severity=Severity.HIGH,
            description="Untrusted user input is concatenated into LDAP search filters.",
            business_impact="Attackers may enumerate directory entries or bypass authentication controls.",
            recommendation="Use parameterized LDAP filters and strict escaping for special characters.",
            reference="https://owasp.org/www-community/attacks/LDAP_Injection",
            owasp_category="A03:2021 - Injection",
            cwe="CWE-90",
            patterns=[
                r"ldap.*search\s*\(.*\+.*\)",
                r"searchFilter\s*=\s*.*\+",
                r"DirContext.*search\s*\(.*\+",
            ],
            file_extensions=CODE_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A05-XXE-001",
            vulnerability_type="XML External Entity (XXE) Risk",
            severity=Severity.HIGH,
            description="XML parsers are used in a way that may allow external entity resolution.",
            business_impact="Attackers may read local files, perform SSRF, or crash backend services.",
            recommendation="Disable external entity resolution and DTD processing in XML parsers.",
            reference="https://owasp.org/www-community/vulnerabilities/XML_External_Entity_(XXE)_Processing",
            owasp_category="A05:2021 - Security Misconfiguration",
            cwe="CWE-611",
            patterns=[
                r"DocumentBuilderFactory\.newInstance\s*\(",
                r"SAXParserFactory\.newInstance\s*\(",
                r"lxml\.etree\.XMLParser\s*\(",
                r"xml\.etree\.ElementTree\.(fromstring|parse)\s*\(",
            ],
            file_extensions=CODE_EXTENSIONS | CONFIG_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A01-MASSASSIGN-001",
            vulnerability_type="Mass Assignment / Object Binding Risk",
            severity=Severity.MEDIUM,
            description="Request body is mapped directly into model objects without field allowlisting.",
            business_impact="Attackers may set privileged attributes such as roles, status flags, or ownership fields.",
            recommendation="Explicitly map allowed fields and reject unknown properties from client input.",
            reference="https://cheatsheetseries.owasp.org/cheatsheets/Mass_Assignment_Cheat_Sheet.html",
            owasp_category="A01:2021 - Broken Access Control",
            cwe="CWE-915",
            patterns=[
                r"(Model|entity|repository)\.(create|update|save)\s*\(\s*(req|request)\.body",
                r"new\s+\w+\s*\(\s*(req|request)\.body",
                r"assign_attributes\s*\(\s*params",
            ],
            file_extensions=CODE_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A01-PROTOTYPE-POLLUTION-001",
            vulnerability_type="Prototype Pollution Risk",
            severity=Severity.HIGH,
            description="Deep merge operations consume untrusted objects without key sanitization.",
            business_impact="Prototype pollution can alter application behavior and lead to privilege escalation.",
            recommendation="Block dangerous keys (__proto__, constructor, prototype) and use safe merge libraries.",
            reference="https://owasp.org/www-project-top-ten/2017/A9_2017-Using_Components_with_Known_Vulnerabilities",
            owasp_category="A08:2021 - Software and Data Integrity Failures",
            cwe="CWE-1321",
            patterns=[
                r"(lodash|_)\.merge\s*\(\s*\{\s*\},\s*(req|request)\.body",
                r"Object\.assign\s*\(\s*\{\s*\},\s*(req|request)\.body",
                r"deepmerge\s*\(.*(req|request)\.body",
            ],
            file_extensions=CODE_EXTENSIONS | WEB_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A05-CORS-001",
            vulnerability_type="Overly Permissive CORS Configuration",
            severity=Severity.HIGH,
            description="Cross-origin access policy appears overly permissive for backend/API responses.",
            business_impact="Untrusted origins may access authenticated API responses and sensitive data.",
            recommendation="Allowlist trusted origins and avoid wildcard origin with credentialed requests.",
            reference="https://owasp.org/Top10/A05_2021-Security_Misconfiguration/",
            owasp_category="A05:2021 - Security Misconfiguration",
            cwe="CWE-942",
            patterns=[
                r"Access-Control-Allow-Origin\s*[:=]\s*['\"]\*['\"]",
                r"allow_origins\s*=\s*\[\s*['\"]\*['\"]\s*\]",
                r"cors\s*\(\s*\{[^}]*origin\s*:\s*['\"]\*['\"]",
            ],
            file_extensions=CODE_EXTENSIONS | CONFIG_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A04-CSRF-001",
            vulnerability_type="CSRF Protection Disabled",
            severity=Severity.HIGH,
            description="CSRF safeguards are explicitly disabled in backend handlers.",
            business_impact="Attackers can force authenticated users to execute unwanted state-changing requests.",
            recommendation="Enable CSRF tokens for browser-based state-changing endpoints.",
            reference="https://owasp.org/www-community/attacks/csrf",
            owasp_category="A04:2021 - Insecure Design",
            cwe="CWE-352",
            patterns=[
                r"@csrf_exempt",
                r"csrf\s*=\s*False",
                r"protect_from_forgery\s+with:\s*:null_session",
            ],
            file_extensions=CODE_EXTENSIONS | CONFIG_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A07-RATELIMIT-001",
            vulnerability_type="Rate Limiting Disabled or Misconfigured",
            severity=Severity.MEDIUM,
            description="Rate limiting appears absent or intentionally disabled in API/backend configuration.",
            business_impact="Brute-force, credential stuffing, and denial-of-service attacks become easier.",
            recommendation="Enforce per-user and per-IP throttling on authentication and sensitive API routes.",
            reference="https://owasp.org/API-Security/editions/2023/en/0xa4-unrestricted-resource-consumption/",
            owasp_category="A07:2021 - Identification and Authentication Failures",
            cwe="CWE-770",
            patterns=[
                r"rateLimit\s*\(\s*\{[^}]*max\s*:\s*0",
                r"throttl(e|ing).*(disable|false|off)",
                r"RATELIMIT_ENABLED\s*[:=]\s*(False|false|0)",
            ],
            file_extensions=CODE_EXTENSIONS | CONFIG_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A09-LOG-LEAK-001",
            vulnerability_type="Sensitive Data Logged",
            severity=Severity.MEDIUM,
            description="Potentially sensitive credentials or tokens are written into logs.",
            business_impact="Leaked logs can expose credentials, sessions, and PII to internal or external attackers.",
            recommendation="Mask sensitive fields and adopt secure structured logging with redaction.",
            reference="https://owasp.org/Top10/A09_2021-Security_Logging_and_Monitoring_Failures/",
            owasp_category="A09:2021 - Security Logging and Monitoring Failures",
            cwe="CWE-532",
            patterns=[
                r"(logger|logging|console)\.(debug|info|warn|error)\s*\(.*(password|secret|token|authorization)",
                r"print\s*\(.*(password|secret|token|authorization)",
            ],
            file_extensions=CODE_EXTENSIONS | CONFIG_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A05-UPLOAD-001",
            vulnerability_type="Unrestricted File Upload Risk",
            severity=Severity.HIGH,
            description="File upload handlers appear to accept files without strict validation controls.",
            business_impact="Attackers may upload executable payloads, malware, or oversized files to compromise systems.",
            recommendation="Validate MIME/extension, scan content, enforce size limits, and store outside web root.",
            reference="https://owasp.org/www-community/vulnerabilities/Unrestricted_File_Upload",
            owasp_category="A05:2021 - Security Misconfiguration",
            cwe="CWE-434",
            patterns=[
                r"request\.files\[[^\]]+\]",
                r"move_uploaded_file\s*\(",
                r"multer\s*\(\s*\)",
                r"IFormFile",
            ],
            file_extensions=CODE_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A03-SSTI-001",
            vulnerability_type="Server-Side Template Injection (SSTI) Risk",
            severity=Severity.HIGH,
            description="Template rendering API is fed directly from user-controlled input.",
            business_impact="Template injection can execute arbitrary code and expose server-side secrets.",
            recommendation="Never render templates directly from user input; use strict context binding and escaping.",
            reference="https://owasp.org/www-project-web-security-testing-guide/",
            owasp_category="A03:2021 - Injection",
            cwe="CWE-1336",
            patterns=[
                r"render_template_string\s*\(\s*(request|req)\.",
                r"Jinja2?\.Template\s*\(\s*(request|req)\.",
                r"Template\s*\(\s*(request|req)\.",
            ],
            file_extensions=CODE_EXTENSIONS | WEB_EXTENSIONS,
        ),
        _rule(
            rule_id="OWASP-A02-COOKIE-001",
            vulnerability_type="Insecure Cookie Security Flags",
            severity=Severity.MEDIUM,
            description="Cookie configuration disables security attributes used for session protection.",
            business_impact="Session tokens become easier to steal via network interception or client-side scripts.",
            recommendation="Set Secure, HttpOnly, and SameSite attributes for all session/authentication cookies.",
            reference="https://owasp.org/www-community/controls/SecureCookieAttribute",
            owasp_category="A02:2021 - Cryptographic Failures",
            cwe="CWE-614",
            patterns=[
                r"set_cookie\s*\(.*secure\s*=\s*False",
                r"set_cookie\s*\(.*httponly\s*=\s*False",
                r"res\.cookie\s*\(.*secure\s*:\s*false",
                r"res\.cookie\s*\(.*httpOnly\s*:\s*false",
            ],
            file_extensions=CODE_EXTENSIONS | CONFIG_EXTENSIONS,
        ),
    ]

